#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Meridional.Resource", IsApplication=true)]

namespace Meridional
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_black_notitlebar_fullscreen_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int btnHotel = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int btnHs0Back = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int btnHs0Next = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int btnRestaurant = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int btnRs0Back = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int btnRs0Next = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int iptHs0enterRoom = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int iptRs0 = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int tvHs0enterRoom = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int tvRs0 = 2131165190;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int hs0_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int rs0_main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int GeneralBack = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int GeneralNext = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int GeneralScore1 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int GeneralScore2 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int GeneralScore3 = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int GeneralScore4 = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int MainHotel = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int MainRestaurant = 2130968579;
			
			// aapt resource value: 0x7f040013
			public const int hsBreakfastQ1 = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int hsBreakfastQ2 = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int hsBreakfastQ3 = 2130968597;
			
			// aapt resource value: 0x7f040012
			public const int hsBreakfastTitle = 2130968594;
			
			// aapt resource value: 0x7f04001b
			public const int hsHotelQ1 = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int hsHotelQ2 = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int hsHotelQ3 = 2130968605;
			
			// aapt resource value: 0x7f04001a
			public const int hsHotelTitle = 2130968602;
			
			// aapt resource value: 0x7f04000b
			public const int hsReceptionQ1 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int hsReceptionQ2 = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int hsReceptionQ3 = 2130968589;
			
			// aapt resource value: 0x7f04000a
			public const int hsReceptionTitle = 2130968586;
			
			// aapt resource value: 0x7f04000f
			public const int hsRoomQ1 = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int hsRoomQ2 = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int hsRoomQ3 = 2130968593;
			
			// aapt resource value: 0x7f04000e
			public const int hsRoomTitle = 2130968590;
			
			// aapt resource value: 0x7f040017
			public const int hsStaffQ1 = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int hsStaffQ2 = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int hsStaffQ3 = 2130968601;
			
			// aapt resource value: 0x7f040016
			public const int hsStaffTitle = 2130968598;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
